---
# tasks file for vector-role
- name: Install Vector distrib
  become: true
  ansible.builtin.yum:
    name: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ arch }}.rpm"
    state: present
- name: Setup vector config
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "/etc/vector/vector.toml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
- name: Vector systemd
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Restart Vector service